# Quick aliases
alias ls='ls -hFvbA --color=always --group-directories-first'
alias grep='grep --color=auto'
alias du='du -h'
alias umount='sudo umount'
alias mkdir='mkdir -p'
alias rm='sudo rm -rv --preserve-root'
alias mv='rsync -rvP --remove-source-files'
alias cp='rsync -rv --progress'
# alias mv='mv -iv'
# alias cp='sudo cp -iv'
alias ln='ln -iv'
alias df='df -Th'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

alias pacman='sudo pacman'
alias pac='pacman'
alias pacs='pacman -S'
# alias pacst='pacman -S --asdeps'
alias pacsy='pacman -S --noconfirm'
alias pacss='pacman -Ss'
alias pacq='pacman -Q'
alias pacqs='pacman -Qs'
alias pacu='pacman -U'
alias paci='pacman -Si'
alias pacr='pacman -Rnsc'
alias pacclear='pacman -Rnsc (pacman -Qtdq); yaourt -Qdt'
alias pacfix='sudo rm -f /var/lib/pacman/db.lck ;and pacman -Syyuu '
# ;and pacman -Suu'
alias yr='yaourt'
alias yrsy='yaourt -S --noconfirm'
alias yrs='yaourt -S'
alias yrss='yaourt -Ss'
alias yrq='yaourt -Q'
alias yrr='yaourt -Rnsc'

# alias up='pacman -Syu ;and yaourt -Su --aur'
alias up='yaourt -Syua' # ;and pacman -Scc'
# alias upy='pacman -Syu --noconfirm ;and yaourt -Su --aur --noconfirm'
# alias upy='yaourt -Syyu --aur --noconfirm'
# alias upyx='yaourt -Syyu --aur --noconfirm; shutdown -h now'
alias upy='yaourt -Syua --noconfirm ;and pacman -Scc'
alias upyx='yaourt -Syua --noconfirm; shutdown -P now'
alias upmiror="sudo curl -s 'https://www.archlinux.org/mirrorlist/?country=UA&protocol=https&use_mirror_status=on' | sed -e 's/^#Server/Server/' > /etc/pacman.d/mirrorlist ; cat /etc/pacman.d/mirrorlist"

alias fishr='source ~/.config/fish/config.fish'
alias dunstr='killall dunst; notify-send "dunst restart" "test critical" -u critical & notify-send "dunst" "test normal" -u normal & notify-send "dunst" "test low" -u low'

alias xprop='xprop | grep -E "^(WM_CLASS|_NET_WM_NAME|WM_NAME)"'
alias xoff='shutdown -P now'
alias x='exit'
# alias usbsw='sudo /usr/sbin/usb_modeswitch -v 12d1 -p 1446 -c /usr/share/usb_modeswitch/12d1:1446'
alias steam="env LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' \
            STEAM_RUNTIME=1 steam"
